### ISSUE TITLE
Clarification ask: timewarp with --timezone  'named timezone' and --match-time: seems --match-time  is ignored when using a 'named timezone'

### ISSUE THREAD

**Issue by oPromessa** [RhetTbull/osxphotos#1777]
**Before submitting a bug report, please ensure you are running the most recent version of osxphotos and that the bug is reproducible on the latest version**
```log
$  osxphotos --version
osxphotos, version 0.69.2
Python 3.12.7 (main, Oct 11 2024, 17:54:25) [Clang 14.0.0 (clang-1400.0.29.202)]
Python executable: /Users/XXX/Documents/GitHub/osxphotos/venv/bin/python
macOS 12.7.6, x86_64
```
**Describe the bug**

Possibly not a bug, maybe an enhancement or I'misreading the timewarp scenarios with --timezone 'named timezone' vs UTCOffset and --match-time: for me it seems --match-time option is ignored when using a 'named timezone'.
* Side Comment: it also seems "--inspect" reports the timestamp shifted and UTC Offset incorrectly and not accounting for DST in test 1. and 3. It should show +02:00 and not +01:00 for UTC Offset.

From help timewarp --timezone we have this note also:
>  Note: when a named timezone is
>  provided, daylight savings time will be
> considered when adjusting the time; it will
> not be considered when a UTC offset is
> provided. For list of valid IANA timezone
> names, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

| Test | initial date_time on Photos | initial --inspect | --timezone | --match-time | final --inspect | final date_time on Photos | Comment | 
| -- | -- | -- | -- | -- | -- | -- | -- |
| 1 | 2017-06-24 21:26:51 GMT+1 | 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon | 'Europe/Madrid' | True | 2017-06-24 21:26:51+0100, +0100, Europe/Madrid | 2017-06-24 22:26:51 CEST | Preferred to have CEST but timestamp is shifted |
| 2 | 2017-06-24 21:26:51 GMT+1 | 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon | UTC Offset +02:00 | True | 2017-06-24 21:26:51+0200, +0200, GMT+0200 | 2017-06-24 21:26:51 GMT+2 | Correct timestamp and timezone. Would like it to be CST | 
| 3 | 2017-06-24 21:26:51 GMT+1 | 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon | 'Europe/Madrid' | False | 2017-06-24 21:26:51+0100, +0100, Europe/Madrid | 2017-06-24 22:26:51 CEST | Same as case 1. Preferred to have CEST but timestamp is shifted | 

**To Reproduce**

### 1. Using 'named timezone' --match-time
<details>
  <summary>Test 1 detail</summary>

```py
$ osxphotos timewarp -i                              
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon, 2017-09-02 22:27:16+0100

$ osxphotos timewarp --timezone 'Europe/Madrid' --verbose --timestamp --match-time  --force
2025-01-08 13:16:15.728033 -- Skipping date/time update for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D), already matches new timezone Europe/Madrid
2025-01-08 13:16:15.783004 -- Updated timezone for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from Europe/Lisbon, offset=3600 to Europe/Madrid, offset=3600
2025-01-08 13:16:15.784026 -- Done.

$ osxphotos timewarp -i                                                                    
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Madrid, 2017-09-02 22:27:16+0100
```

</details>

### 2. Using 'UTC Offset' --match-time

<details>
  <summary>Test 2 detail</summary>

```py
$ osxphotos timewarp -i                                                                   
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon, 2017-09-02 22:27:16+0100

$ osxphotos timewarp --timezone '+02:00' --verbose --timestamp --match-time  --force       
2025-01-08 13:34:17.978847 -- Adjusted local date/time for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) to 2017-06-24 20:26:51 to match previous time 2017-06-24 21:26:51 but in new timezone GMT+0200.
2025-01-08 13:34:17.982241 -- Photo date/time is now 2017-06-24 20:26:51 in new timezone GMT+0200.
2025-01-08 13:34:18.043436 -- Updated timezone for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from Europe/Lisbon, offset=3600 to GMT+0200, offset=7200
2025-01-08 13:34:18.044173 -- Done.

$ NOk.2017 [1102]> osxphotos timewarp -i                                                             
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 20:26:51+0100, 2017-06-24 21:26:51+0200, +0200, GMT+0200, 2017-09-02 22:27:16+0100
```

</details>

### 3. Using 'named timezone' 
<details>
  <summary>Test 3 detail</summary>

```py
$ osxphotos timewarp -i                                        
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon, 2017-09-02 22:27:16+0100

$ osxphotos timewarp --timezone 'Europe/Madrid' --verbose --timestamp --force              
2025-01-08 13:40:48.517488 -- Updated timezone for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from Europe/Lisbon, offset=3600 to Europe/Madrid, offset=3600
2025-01-08 13:40:48.518577 -- Done.

$ osxphotos timewarp -i                                                      
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Madrid, 2017-09-02 22:27:16+0100
```

</details>

#### In Photos in the Photo Info (enabling display of timezone on the Mac Regional Settings): 2017-06-24 22:26:51 CEST

**Expected behavior**
Would like to use --timezone 'named timezone' (respecting DST) and being able to use --match-time to keep the same timestamp.

**Screenshots**
N/A

**Desktop (please complete the following information):**
```py
$ sw_vers 
ProductName:	macOS
ProductVersion:	12.7.6
BuildVersion:	21H1320
```

**Additional context**

**Comment by oPromessa** [comment]
A possible workaround would be to use `--time-delta DELTA` with `-01 hour` for Test 1 case.

Result: In Photos is okay! timewarp -i still shows the shifted time with UTCOffset  +01:00 as I think is not considering DST.

#### In Photos in the Photo Info (enabling display of timezone on the Mac Regional Settings): 2017-06-24 21:26:51 CEST

```py
$ osxphotos timewarp -i                                                                      
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 21:26:51+0100, 2017-06-24 21:26:51+0100, +0100, Europe/Lisbon, 2017-09-02 22:27:16+0100

$ osxphotos timewarp --timezone 'Europe/Madrid' --verbose --timestamp --time-delta '-01 hours'  --force
2025-01-08 14:18:52.141249 -- Updated date/time for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from: 2017-06-24 21:26:51+01:00 to 2017-06-24 20:26:51+01:00
2025-01-08 14:18:52.202521 -- Updated timezone for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from Europe/Lisbon, offset=3600 to Europe/Madrid, offset=3600
2025-01-08 14:18:52.203266 -- Done.

$ osxphotos timewarp -i                                                                                
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_20170624_212651.JPG, 8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D, 2017-06-24 20:26:51+0100, 2017-06-24 20:26:51+0100, +0100, Europe/Madrid, 2017-09-02 22:27:16+0100
```

**Comment by RhetTbull** [comment]
I'll take a look. Likely a bug. I completely rewrote this part of the code a few months ago and it was extremely tricky to get right. My least favorite topic in programming is working with timezones!

**Comment by oPromessa** [comment]
I get you! 😆 

I guess not, but would time warp be able to operate over a specific photo (either with --uuid or --name or --album)?

Or could I import timewarp from a python app and provide one by one the pics?

Hmmm. I guess a combination of show and timewarp could do the trick! Hmmm. No. Show does not actually select the image.

**Comment by RhetTbull** [comment]
> but would time warp be able to operate over a specific photo (either with --uuid or

Yes, you can use `--uuid` with timewarp as well as `-uuid-from-file`

**Comment by oPromessa** [comment]
::embarrassing:: 😃 not to have fully read the doc and looking for --uuid. 

The initial description for timewarp through me off: "Changes will be applied to all photos currently selected in Photos."

What I see happening is that timewarp runs over the --uuid specified IDs _plus_ the selected pics as it shows me the total pics tone  

```py
$ osxphotos timewarp  --uuid 70D3637B-1321-4AB5-93FC-6C4EB214BA23 --timezone 'Europe/Madrid' --time-delta '-3600 seconds'
⚠️  About to process 3 photos with timewarp. This will directly modify your 
Photos library database using undocumented features. While this functionality 
(...)
```

But now that I know about it it will make my life SOOO MUCH EASIER to update thousands of wrong timezones pics!

**Comment by RhetTbull** [comment]
Yes, I should update the help text. Also, I think if `--uuid` is used then the current selection should not be used. I'll open a new issue for this.

I've been thinking about how to make `batch-edit` and `timewarp` (and any future commands that operate on selected photos) more useful. One idea I'm thinking of is something like this to use `osxphotos query`:

`osxphotos query --query-options --uuid-only | osxphotos timewarp --uuid-from-file -`

This would pipe a list of uuids to timewarp for processing. This avoids having to clutter timewarp with all the query options. It would require a new option for `osxphotos query` that prints only uuid. (This can be accomplished today with `osxphotos query --print "{uuid}" --quiet` but that's cumbersome). Open to feedback on improving this approach.

**Comment by oPromessa** [comment]
> I'll take a look. Likely a bug. I completely rewrote this part of the code a few months ago and it was extremely tricky to get right. My least favorite topic in programming is working with timezones!

Did a few more tests and I thing issue is with DST. 

Lisbon TZ with DST offset is 3600
Madrid TZ without DST is 3600 -- but with DST is  7200

I guess on this line one should calculate the delta taking DST into consideration. Today I'm not feeling capable of working it out 😸 -- and there maybe side impacts I'm not aware! Do you agree this is the place? Some guidance from ou and maybe I can give it a try !!

https://github.com/RhetTbull/osxphotos/blob/56a6601b5d26527bf57802e0c44fe7f6a8decb01/osxphotos/photodates.py#L209-L215

```py
$ osxphotos timewarp --timezone 'Europe/Madrid' --verbose --timestamp --match-time  --force
2025-01-08 13:16:15.728033 -- Skipping date/time update for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D), already matches new timezone Europe/Madrid
2025-01-08 13:16:15.783004 -- Updated timezone for photo IMG_20170624_212651.JPG (8984A3C1-EFD5-4AB2-9DB4-B39D32C48E3D) from Europe/Lisbon, offset=3600 to Europe/Madrid, offset=3600
2025-01-08 13:16:15.784026 -- Done.
```

**Comment by RhetTbull** [comment]
I think I see the problem. It's not actually in this part of the code. The old timezone offset is determined from the Photos database so that is considered "truth data". The new timezone offset is determined by the `Timezone` class.

The Timezone for the new timezone is created here:

https://github.com/RhetTbull/osxphotos/blob/56a6601b5d26527bf57802e0c44fe7f6a8decb01/osxphotos/photodates.py#L300-L301

The offset gets computed here (but doesn't account for DST, it returns just the offset for the standard timezone):

https://github.com/RhetTbull/osxphotos/blob/56a6601b5d26527bf57802e0c44fe7f6a8decb01/osxphotos/photodates.py#L209-L212

What's needed is to add here an `offset_for_date(self, date: datetime.datetime) -> int:` method that returns the offset for a given date. It should call the `secondsFromGMTForDate_` method of `NSTimeZone`. For consistency, it should also include an `offset_str_for_date(self, date: datetime.datetime)->str:` method.

https://github.com/RhetTbull/osxphotos/blob/56a6601b5d26527bf57802e0c44fe7f6a8decb01/osxphotos/timezones.py#L38-L68

**Comment by RhetTbull** [comment]
@oPromessa I'm going to need to fix this for another branch I'm working on to fix import time / timezone (#849 and #1661) so I'll update the fix for DST here as well.

**Comment by oPromessa** [comment]
> @oPromessa I'm going to need to fix this for another branch I'm working on to fix import time / timezone (#849 and #1661) so I'll update the fix for DST here as well. 

Hey @RhetTbull would you want me to help you on this one -- I might need some pointers on how to address it 😃 !

**Comment by RhetTbull** [comment]
Hi @oPromessa I think this is fixed in another branch I'm working. Just need to add a test. I've been extremely busy so not able to get this branch merged. Will try to get to it soon.

**Comment by oPromessa** [comment]
> I think I see the problem. It's not actually in this part of the code. The old timezone offset is determined from the Photos database so that is considered "truth data". The new timezone offset is determined by the `Timezone` class.

As method _update_photo  from class  `PhotoTimeZoneUpdater` is used in multiple locations I wanted to pick your brain to know if this is not going to wrongly affect things.
 
I noticed the `main` branch already has the `offset_for_date` method on the `Timezone` class,  that accounts for DST for a given date. YAY!!!

I was trying to get this going and wanted to validate that one also needs to apply on the `_update_photo` method for class  `PhotoTimeZoneUpdater`: 

https://github.com/RhetTbull/osxphotos/blob/05adfe4f9ae57ce939a8b192ffb0f16e9453d0fe/osxphotos/phototz.py#L149-L154

...the `offset_for_date` for the given `photo.date`

```py
         ) as conn: 
             c = conn.cursor() 
             c.execute(sql) 
             results = c.fetchone() 

         self.tz_offset = self.timezone.offset_for_date(photo.date)  

         if results[2] == self.tz_offset and results[3] == self.tz_name: 
```

It would maybe make sense to have it on the  `__init__` function of class PhotoTimeZoneUpdater but the actual photo.date is not available at that time as photo is not an argument.

https://github.com/RhetTbull/osxphotos/blob/05adfe4f9ae57ce939a8b192ffb0f16e9453d0fe/osxphotos/phototz.py#L90-L99

**Comment by RhetTbull** [comment]
> It would maybe make sense to have it on the  __init__ function of class PhotoTimeZoneUpdater but the actual photo.date is not available at that time as photo is not an argument.

@oPromessa this is because the `PhotoTimeZoneUpdater` is used in `osxphotos timewarp` to batch update a batch of photos with a given timezone.

I have made significant changes to all the timezone code in another working branch and and working through a couple failing tests to get this released. Unfortunately I've only got a couple hours a week lately to work on osxphotos so it's going slowly. As soon as I get that branch merged we can verify that it fixes this issue and if not, implement you changes. Until then any changes to any of the timezone code will cause merge conflicts.

**Comment by RhetTbull** [comment]
I have 1 failing test left before I can push these changes!

```
FAILED tests/test_cli_timewarp.py::test_pull_exif_no_data_use_file_time - AssertionError: assert CompareValues(filename='IMG_6506.jpeg', uuid='7E9DF2EE-A5B0-4077-80EC-30565221A3B9', date_photos='2024-11-26 07:43:44', date_exif='', tz_offset_photos=...
```

Getting close...

**Comment by RhetTbull** [comment]
I'm getting close to being able to tackle this. I've gotten the new timewarp code working (but still one new issue #1839) and working now to get `osxphotos import` to use the new code from timewarp (which accounts for timezone when parsing a date from the filename with `--parse-date`). Once that is done, I think I can tackle this. (I think it's been fixed but have not created a test yet).

**Comment by RhetTbull** [comment]
@oPromessa I think this is fixed in main.  Working on a couple other issues then will try to push out a release this week.

**Comment by oPromessa** [comment]
Super. Will try to run some of my use cases meanwhile. Thanks so much.

**Comment by oPromessa** [comment]
@RhetTbull  From a quick test of two photos, say from Madrid, one in July (DST enabled) and one from December (no DST) I still don't get the proper setting for the 'no DST' pic.

I must change the following code on phototz.py to make it work. From:

https://github.com/RhetTbull/osxphotos/blob/75cd09163b21def317e4214a8a7a762ae710ce73/osxphotos/phototz.py#L149-L158

To: 

```py
          ) as conn:
              c = conn.cursor()
              c.execute(sql)
              results = c.fetchone()
    
          tz_offset_dst = self.timezone.offset_for_date(photo.date)
          self.tz_offset = tz_offset_dst
    
          if results[2] == self.tz_offset and results[3] == self.tz_name:
              self.verbose(
                  f"Skipping timezone update for photo [filename]{photo.filename}[/filename] ([uuid]{photo.uuid}[/uuid]): nothing to do"
              )
              return
```

Any thoughts?

<details>
  <summary>Some tests without my code change!</summary>

```py

$ osphotos timewarp -i
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_1693.tif, 6855A974-AC67-407B-9790-5AADE614ABDA, 2020-07-12 10:47:13+0100, 2020-07-12 04:47:13-0500, -0500, America/Mexico_City, 2025-05-01 00:03:38+0100
IMG_3092.heic, DE7B9D90-5B5F-428E-AB72-C234CCE12DBC, 2020-12-19 05:36:26+0000, 2020-12-18 23:36:26-0600, -0600, America/Mexico_City, 2025-05-01 00:03:34+0100

$ echo Change the GPS Location to Brussels in Photos. Press enter to continue...

$ osxphotos timewarp --uuid 6855A974-AC67-407B-9790-5AADE614ABDA --timezone 'Europe/Brussels' --match-time --force --verbose
Adjusted local date/time for photo IMG_1693.tif (6855A974-AC67-407B-9790-5AADE614ABDA) to 2020-07-12 03:47:13 to match previous time 2020-07-12 10:47:13 but in new timezone Europe/Brussels.
Photo date/time is now 2020-07-12 04:47:13+02:00 in new timezone Europe/Brussels.
Updated timezone for photo IMG_1693.tif (6855A974-AC67-407B-9790-5AADE614ABDA) from America/Mexico_City, offset=-18000 to Europe/Brussels, offset=7200
Done.

$ osxphotos timewarp --uuid DE7B9D90-5B5F-428E-AB72-C234CCE12DBC --timezone 'Europe/Brussels' --match-time --force --verbose
Adjusted local date/time for photo IMG_3092.heic (DE7B9D90-5B5F-428E-AB72-C234CCE12DBC) to 2020-12-18 22:36:26 to match previous time 2020-12-19 05:36:26 but in new timezone Europe/Brussels.
Photo date/time is now 2020-12-18 23:36:26+01:00 in new timezone Europe/Brussels.
Updated timezone for photo IMG_3092.heic (DE7B9D90-5B5F-428E-AB72-C234CCE12DBC) from America/Mexico_City, offset=-21600 to Europe/Brussels, offset=7200
Done.
                                         ^^^^^
                                         Here it does sate the correct time: 2020-12-18 23:36:26+0100 ;  But offset still states 7200

$ osxphotos timewarp -i
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_1693.tif, 6855A974-AC67-407B-9790-5AADE614ABDA, 2020-07-12 03:47:13+0100, 2020-07-12 04:47:13+0200, +0200, Europe/Brussels, 2025-05-01 00:03:38+0100
IMG_3092.heic, DE7B9D90-5B5F-428E-AB72-C234CCE12DBC, 2020-12-18 22:36:26+0000, 2020-12-19 00:36:26+0200, +0200, Europe/Brussels, 2025-05-01 00:03:34+0100
                                                                                 ^^^^^
                                                                                 It should be 2020-12-18 23:36:26+0100

```

</details>

**Comment by RhetTbull** [comment]
Thanks for the testing. You're right that getting the offset for the date is needed but I thought I was doing that in `update_photo_time_for_new_timezone()` which is called for match time. I'll take a look to see what's going on. I'd added a test case I thought covered this but I guess not.

**Comment by RhetTbull** [comment]
@oPromessa I think there are actually 2 bugs, one in `update_photo_time_for_new_timezone` which I've fixed and one in the `PhotoTimezoneUpdater` as you identified. I'm working on the second one now.

**Comment by oPromessa** [comment]
Thanks so much for looking into this.

**Comment by oPromessa** [comment]
From my tests it looks WONDERFUL!!! Thank you so much for the hard-work!

Just FYI, I've ran `python -m pytest -v tests/test_cli_timewarp.py --timewarp` and the only failing test is `test_video_date` when the IMG_6551.mov is set by date only `--date 2021-10-04` and  the result date is off by 1 day. Maybe because my timezone is WEST (+0100) and PST vs WEST are off by one day for certain hours of the day.

<details>
<summary>(click for details) 

```py
FAILED tests/test_cli_timewarp.py::test_video_date[2021-10-04-2021-10-04 20:01:03-0700] - AssertionError: assert '2021-10-03 20:01:03-0700' == '2021-10-04 20:01:03-0700'
```

</summary>

```py
================================================================= FAILURES ==================================================================
___________________________________________ test_video_date[2021-10-04-2021-10-04 20:01:03-0700] ____________________________________________

photoslib = <photoscript.PhotosLibrary object at 0x1162f01d0>
suspend_capture = <tests.conftest.suspend_capture.<locals>.suspend_guard object at 0x1162f1310>, input_value = '2021-10-04'
expected = '2021-10-04 20:01:03-0700'

    @pytest.mark.timewarp
    @pytest.mark.parametrize("input_value,expected", TEST_DATA["video_date"]["parameters"])
    def test_video_date(photoslib, suspend_capture, input_value, expected):
        """Test --date with video"""
    
        runner = CliRunner()
        result = runner.invoke(
            timewarp,
            [
                "--date",
                input_value,
                "--plain",
                "--force",
                "--uuid",
                UUID_DICT["sunset_video"],
            ],
            terminal_width=TERMINAL_WIDTH,
        )
        assert result.exit_code == 0
        # inspect to get the updated times
        # don't use photo.date as it will return local time instead of the time in the timezone
        result = runner.invoke(
            timewarp,
            ["--inspect", "--plain", "--force", "--uuid", UUID_DICT["sunset_video"]],
            terminal_width=TERMINAL_WIDTH,
        )
        output_values = parse_inspect_output(result.output)
>       assert output_values[0].date_tz == expected
E       AssertionError: assert '2021-10-03 20:01:03-0700' == '2021-10-04 20:01:03-0700'
E         - 2021-10-04 20:01:03-0700
E         ?          ^
E         + 2021-10-03 20:01:03-0700
E         ?          ^

tests/test_cli_timewarp.py:916: AssertionError
========================================================== short test summary info ==========================================================
FAILED tests/test_cli_timewarp.py::test_video_date[2021-10-04-2021-10-04 20:01:03-0700] - AssertionError: assert '2021-10-03 20:01:03-0700' == '2021-10-04 20:01:03-0700'
================================================== 1 failed, 56 passed in 86.68s (0:01:26) ==================================================
```

</details>

**Comment by RhetTbull** [comment]
@oPromessa  Would you mind running the test suite again to see if it still fails? I recently upgraded my Mac and noticed intermittent failures with timewarp. I suspect it's due to machine speed running the check before Photos can sync the changes but have not diagnosed root cause yet. I've not noticed errors in actual use, only in the tests.

**Comment by oPromessa** [comment]
> Just FYI, I've ran `python -m pytest -v tests/test_cli_timewarp.py --timewarp` and the only failing test is `test_video_date` when the IMG_6551.mov is set by date only `--date 2021-10-04` and the result date is off by 1 day. Maybe because my timezone is WEST (+0100) and PST vs WEST are off by one day for certain hours of the day.

Error still occurs to me in pytest --timewarp. Had some time to run a debug session but was not able to grasp the issue.

I attach a PDF with the snippets of the debug session in case it is helpful.

[1777.pdf](https://github.com/user-attachments/files/20173530/1777.pdf)

**Comment by RhetTbull** [comment]
Thanks for the data -- I'll take a look. It could be just a badly written test but either way will want to fix it.

**Comment by RhetTbull** [comment]
@oPromessa  I've confirmed this is a bug. Thanks again for the detailed debugging details.

I set my Mac timezone to CET and get the same results you are.

```
UUID = 16BEC0BE-4188-44F1-A8F1-7250E978AD12

Initial state:
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-05 05:00:00+0200, 2021-10-04 20:00:00-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200

Resetting date/time/timezone
Done.
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-05 04:01:03+0200, 2021-10-04 19:01:03-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200

Video date delta -1 day
Done.
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-04 04:01:03+0200, 2021-10-03 19:01:03-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200

Video time delta +1 hour
Done.
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-04 05:01:03+0200, 2021-10-03 20:01:03-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200

Video date: 2021-10-04
Done.
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-04 05:01:03+0200, 2021-10-03 20:01:03-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200

Video time: 20:00:00
Done.
filename, uuid, photo time (local), photo time, timezone offset, timezone name, date added (local)
IMG_6551.mov, 16BEC0BE-4188-44F1-A8F1-7250E978AD12, 2021-10-05 05:00:00+0200, 2021-10-04 20:00:00-0700, -0700, GMT-0700, 2021-10-09 19:35:03+0200
```

The following script runs the timezone commands in sequence so I can test this:

```bash
#!/bin/bash

OSXPHOTOS="python -m osxphotos"
UUID=$(OSXPHOTOS query --quiet --print '{uuid}' --name IMG_6551.mov)

echo "UUID = $UUID"
echo ""
echo "Initial state:"
$OSXPHOTOS timewarp --inspect --uuid $UUID

echo ""
echo "Resetting date/time/timezone"
$OSXPHOTOS timewarp --date "2021-10-04" --time "19:01:03" --timezone "-0700" --force --uuid $UUID
$OSXPHOTOS timewarp --inspect --uuid $UUID

echo ""
echo "Video date delta -1 day"
$OSXPHOTOS timewarp --date-delta "-1 day" --force --uuid $UUID
$OSXPHOTOS timewarp --inspect --uuid $UUID

echo ""
echo "Video time delta +1 hour"
$OSXPHOTOS timewarp --time-delta "+1 hour" --force --uuid $UUID
$OSXPHOTOS timewarp --inspect --uuid $UUID

echo ""
echo "Video date: 2021-10-04"
$OSXPHOTOS timewarp --date "2021-10-04" --force --uuid $UUID
$OSXPHOTOS timewarp --inspect --uuid $UUID

echo ""
echo "Video time: 20:00:00"
$OSXPHOTOS timewarp --time "20:00:00" --force --uuid $UUID
$OSXPHOTOS timewarp --inspect --uuid $UUID
```

I'll do some more digging to figure out where the problem is. As you pointed out it's likely in `update_photo_time_for_new_timezone`.

**Comment by RhetTbull** [comment]
OK, I think I have this finally fixed. This will also fix daylight savings adjustments so they work correctly (see example below). I need to add a couple more test cases then will try to merge and release this week.

If in Europe/Madrid on 2024-03-031, Setting a time delta of 1 hour from 2024-03-31 01:00:00+01:00 now correctly sets the time ahead *2 hours* and changes the timezone  2024-03-31 03:00:00+02:00, account for daylight savings time.

```
$ osxphotos timewarp --force --verbose --date 2024-03-30 --time 23:00:00 --timezone "Europe/Madrid"

Updated date/time for photo IMG_6520.jpeg (53615D56-91F7-4908-81F1-B93B5DEA7449) from: 2017-12-24 21:26:51+01:00 to 2024-03-30 23:00:00+01:00

$ osxphotos timewarp --force --verbose --time-delta "+2 hours"

Updated date/time for photo IMG_6520.jpeg (53615D56-91F7-4908-81F1-B93B5DEA7449) from: 2024-03-30 23:00:00+01:00 to 2024-03-31 01:00:00+01:00

$ osxphotos timewarp --force --verbose --time-delta "+1 hour"

Updated date/time for photo IMG_6520.jpeg (53615D56-91F7-4908-81F1-B93B5DEA7449) from: 2024-03-31 01:00:00+01:00 to 2024-03-31 03:00:00+02:00
```

**Comment by RhetTbull** [comment]
@oPromessa let's try this again! I have ripped out a lot of the datetime handling and replaced with [whenever](https://whenever.readthedocs.io/en/latest/) which correctly works across DST boundaries. The python standard library datetime and timedelta do not respect DST changes when performing math. I've added test cases for timewarp to test both settiing a new date using `--date` or `--time` that causes a DST boundary to be crossed as well as using `--time-delta`  and `--date-delta`. I changed my computer timezone to Madrid and all timezone tests pass. Hopefully this solves the problem you were seeing!

**Comment by oPromessa** [comment]
This is amazing. Will test it later today...

**Comment by oPromessa** [comment]
This is awesome. Ran the tests on WEST timezone:

```py
$ osxphotos --version
osxphotos, version 0.71.0
Python 3.12.9 (main, Feb  4 2025, 14:38:38) [Clang 16.0.0 (clang-1600.0.26.6)]
Python executable: /Users/XXX/Documents/GitHub/osxphotos/venv/bin/python
macOS 15.5.0, x86_64
(venv) 

$ python -m pytest -v tests/test_cli_timewarp.py --timewarp
(...)
===== 59 passed in 130.43s (0:02:10) ======

$  python -m pytest   
(...)
==== 2430 passed, 249 skipped, 8 xfailed, 4 xpassed in 371.63s (0:06:11) ===
```
