### ISSUE TITLE
inspect command fails if a photo in a shared album is selected | version 0.74.0 on macOS 26.1

### ISSUE THREAD

**Issue by Ben-Voris** [RhetTbull/osxphotos#2006]
<https://github.com/RhetTbull/osxphotos/issues/2003> might be related.

## Describe the bug
`osxphotos inspect` fails if a picture in a shared album is selected or opened.

### To Reproduce

Run `./osxphotos inspect`, when a picture in a shared album is selected or opened.

### Command

```shell
`./osxphotos inspect
```

### Error

```text
╭────────────────────────────── Traceback (most recent call last) ───────────────────────────────╮
│ in <module>:18                                                                                 │
│                                                                                                │
│ in __call__:1462                                                                               │
│                                                                                                │
│ in main:1383                                                                                   │
│                                                                                                │
│ in invoke:1850                                                                                 │
│                                                                                                │
│ in invoke:1246                                                                                 │
│                                                                                                │
│ in invoke:814                                                                                  │
│                                                                                                │
│ in photo_inspect:568                                                                           │
│                                                                                                │
│ in inspect_photo:208                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: sequence item 0: expected str instance, NoneType found
[PYI-46219:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

## Expected behavior

`osxphotos` should either display information about the shared photo or should say that it cannot display the information. It should not fail.

## Version

```text
osxphotos, version 0.74.0
Python 3.14.0 (main, Oct 10 2025, 12:54:13) [Clang 20.1.4 ]
Python executable: /private/tmp/osxphotos
macOS 26.1.0, arm64
```

**Comment by RhetTbull** [comment]
I can't test this as I don't have macOS 26.1 on my machine but I think the issue is fixed in v0.74.1. Give it a try and let me know if it is working.

**Comment by mybizgeek** [comment]
@RhetTbull `osxphotos inspect` seems to work with shared photos now. Shared albums are still not being listed with `osxphotos albums` though. Thanks!

**Comment by RhetTbull** [comment]
Thanks. I'm tracking the shared album issue with #2003. Not sure yet what's going on as I don't have access to a machine with 26.1 and shared albums.

**Comment by RhetTbull** [comment]
Can you run this command and send me the output, also identify the name of one or two shared albums:

`sqlite3 --header  ~/Pictures/Photos\ Library.photoslibrary/database/Photos.sqlite "SELECT * FROM ZGENERICALBUM;" > albums.csv`

You can send albums.csv to osxphotos.py@gmail.com
