### ISSUE TITLE
Can't open a photo library on MacOS 10.14.6 with osxphotos

### ISSUE THREAD

**Issue by fokki200** [RhetTbull/osxphotos#230]
Issue is with just one photo library, did run the Repair from the Photos.app but error still occurs.

Error when opening this particular library:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/osxphotos", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/__main__.py", line 1061, in query
    photos = _query(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/__main__.py", line 1870, in _query
    photosdb = osxphotos.PhotosDB(dbfile=db)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/photosdb/photosdb.py", line 305, in __init__
    self._process_database4()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/photosdb/photosdb.py", line 1301, in _process_database4
    for pname in sorted(
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

**Comment by RhetTbull** [comment]
Hi @fokki200 -- thanks for the bug report.  I'm not able to test because I don't the Photos library in question but I think I've fixed this in v0.34.5 so give it another try and let me know if it works.

**Comment by fokki200** [comment]
Thanks for the quick response.
Just installed version v0.34.5, still get an error but it is another one. 

Let me know if you'd like to receive some more information!

Had a quick look myself  and  the "volume" key is missing for some photos.
Noticed that not all photos where consolidated and when trying to, some photos could not be found.. might be the reason

See below for the error logging

When adding an extra check,  if "volume" in info:,  on lines 1321 and 1364 in photosdb.py, the program does no longer throw an exception 

$ osxphotos -v
osxphotos, version 0.34.5
$ osxphotos --db Photos.photoslibrary info
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/osxphotos", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/__main__.py", line 717, in info
    photosdb = osxphotos.PhotosDB(dbfile=db)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/photosdb/photosdb.py", line 305, in __init__
    self._process_database4()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/osxphotos/photosdb/photosdb.py", line 1322, in _process_database4
    self._dbvolumes[info["volumeId"]]
KeyError: 0

**Comment by RhetTbull** [comment]
Could you try the following two sql queries and email me the results (rturnbull+git@gmail.com):

`sqlite3 Photos.photoslibrary/database/Photos.db "select RKVolume.modelId, RKVolume.name from RKVolume" > volumes.txt`

`sqlite3 Photos.photoslibrary/database/Photos.db "select Uuid, volumeID from RKMaster" > volumeid.txt`

The first should be rather short and the latter may be rather long.  This will help in debugging.  I can catch the error in the code but I want to make sure the database is being properly parsed.  I've tested many Photos databases on Mojave and never seen either of these errors.

**Comment by RhetTbull** [comment]
@fokki200   I added a partial fix in v0.35.1.  I'll need additional debugging data to do much more.  Let me know if this fixes your issue.
