### ISSUE TITLE
Move to poetry for setup

### ISSUE THREAD

**Issue by RhetTbull** [RhetTbull/osxphotos#826]
pip is starting to complain about projects with setup.py, need to move to pyproject.toml

**Comment by oPromessa** [comment]
Don't know  if related. Possibly not as you mention Poetry and I'm using uv. But I guess the underlying issue may be the same, no?

I have a few tools I've built on top of osxphotos and started using pyproject.toml and uv on macOS 26.4.
* Everything looks great with python 3.12
* Issue is with python > 3.13: where it starts complaining about the inability to build pyobj-* because pkg_resources is not referenced/available by osxphotos
* `uv tool install` and `uv pip install osxphotos` continue to work okay on Python 3.13.

### Question? AFAYK, this would be something to address solely on osxphotos or would there be any workaround? Until then, I'll stay put on python 3.12!

### In this case, I'm setting up my dev environment to allow --editable packages and then for production I use `uv tool install mytool` to install it.

```bash
$ uv venv --clear --python 3.13 
$ uv sync --all-packages --group dev --python 3.13 
Using CPython 3.13.11 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
Resolved 118 packages in 8ms
  × Failed to build `pyobjc-framework-quartz==9.2`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

  (...)
      "/Users/USERNAME/.cache/uv/sdists-v9/pypi/pyobjc-framework-quartz/9.2/6ia9VDVw_7iBJlJrPBjfV/src/pyobjc_setup.py",
      line 15, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'

      hint: This error likely indicates that `pyobjc-framework-quartz@9.2` depends on `pkg_resources`, but
      doesn't declare it as a build dependency. If `pyobjc-framework-quartz` is a first-party package, consider
      adding `pkg_resources` to its `build-system.requires`. Otherwise, either add it to your `pyproject.toml`
      under:

      [tool.uv.extra-build-dependencies]
      pyobjc-framework-quartz = ["pkg_resources"]

      or `uv pip install pkg_resources` into the environment and re-run with `--no-build-isolation`.
  help: `pyobjc-framework-quartz` (v9.2) was included because `check-timezone` (v0.3.0) depends on `osxphotos`
        (v0.75.6) which depends on `pyobjc-framework-quartz`
```

### File Structure
```bash
- pyproject.toml
| -- tools/check_timezone/
       | -- pyproject.toml
| -- tools/check_timezone/check_timezone
       | -- check_timezone.py
```


### <summary> Full Error

<details> 

Using CPython 3.13.11 interpreter at: /opt/homebrew/opt/python@3.13/bin/python3.13
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
Resolved 118 packages in 8ms
  × Failed to build `pyobjc-framework-quartz==9.2`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta.build_wheel` failed (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
          requires = get_requires_for_build({})
        File "/Users/USERNAME/.cache/uv/builds-v0/.tmpLDo27D/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/USERNAME/.cache/uv/builds-v0/.tmpLDo27D/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/Users/USERNAME/.cache/uv/builds-v0/.tmpLDo27D/lib/python3.13/site-packages/setuptools/build_meta.py",
      line 317, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 52, in <module>
        File
      "/Users/USERNAME/.cache/uv/sdists-v9/pypi/pyobjc-framework-quartz/9.2/6ia9VDVw_7iBJlJrPBjfV/src/pyobjc_setup.py",
      line 15, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'

      hint: This error likely indicates that `pyobjc-framework-quartz@9.2` depends on `pkg_resources`, but
      doesn't declare it as a build dependency. If `pyobjc-framework-quartz` is a first-party package, consider
      adding `pkg_resources` to its `build-system.requires`. Otherwise, either add it to your `pyproject.toml`
      under:

      [tool.uv.extra-build-dependencies]
      pyobjc-framework-quartz = ["pkg_resources"]

      or `uv pip install pkg_resources` into the environment and re-run with `--no-build-isolation`.
  help: `pyobjc-framework-quartz` (v9.2) was included because `check-timezone` (v0.3.0) depends on `osxphotos`
        (v0.75.6) which depends on `pyobjc-framework-quartz`

```

</details>

</summary>


### <summary>  Relevant files: main pyproject.toml

<details> 

```toml
[project]
name = "photos-tools"
version = "0.3.0"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "tools/check_timezone",
]

[dependency-groups]
dev = [
    "black",
    "bump-my-version",
    "flake8",
    "isort",
    "pytest",
]

[tool.bumpversion]
current_version = "0.3.0"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

# check_timezone
[[tool.bumpversion.files]]
filename = "tools/check_timezone/pyproject.toml"
```

</details>

</summary>

### <summary>  Relevant files: Main pyproject.toml

It has entries/referenes to bump-my-version which I believe to be innocuous.

<details> 

```toml
[project]
name = "photos-tools"
version = "0.3.0"
requires-python = ">=3.13"
dependencies = []

[tool.uv]
package = false

[tool.uv.workspace]
members = [
    "tools/check_timezone",
]

[dependency-groups]
dev = [
    "black",
    "bump-my-version",
    "flake8",
    "isort",
    "pytest",
]

[tool.bumpversion]
current_version = "0.3.0"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

# check_timezone
[[tool.bumpversion.files]]
filename = "tools/check_timezone/pyproject.toml"
```

</details>
</summary>


### <summary>  Relevant files: tools/check_timezone/pyproject.toml


I added `[tool.uv.extra-build-dependencies]`with `pyobjc-framework-quartz = ["setuptools"]`in an attempt to force installing setup tools and pkg_resources. But same error.

<details> 

```toml
[project]
name = "check_timezone"
version = "0.3.0"
description = "Checks and fixes timezone inconsistencies in photos managed by the Photos app on macOS."
requires-python = ">=3.12"
dependencies = [
    "click",
    "osxphotos",
    "pytz",
    "rich",
    "timezonefinder",
]

[project.scripts]
check_timezone = "check_timezone.check_timezone:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.extra-build-dependencies]
pyobjc-framework-quartz = ["setuptools"]
```

</details>
</summary>

**Comment by RhetTbull** [comment]
Since this issue was opened, I've switched to uv for everything so would do that vs poetry. I'll look into the uv issues you reference. I am running python 3.14 on macOS with no issue.

**Comment by oPromessa** [comment]
> I am running python 3.14 on macOS with no issue.

Hmmm... are you already on macOS 26.4 ?

**Comment by RhetTbull** [comment]
No. Still on Sequoia

**Comment by oPromessa** [comment]
### Took a second look at the logs. 

Issue seems to be related with pyobjc-framework-quartz.
To be compatible with Python 3.13 it cannot make use of pkg_resources, and this requires pyobjc-framework-quartz>=10.0.

### Works with this test
I tested setting requirements.txt and setup.py on osxphotos to require pyobjc-framework-quartz>=10.0 which resulted in installing pyobjc-framework-quartz version 12.1 and installing my code with the osxphotos dependencies on Python 3.13 nicely.

### Puzzled!
Now the thing is, the previous requirement was  pyobjc-framework-quartz>=9.0 so it should have picked up 12.1... but no, it went and got 9.2, not compatible with Python 3.13, hence the error.

### Test details 

Did a test by changing requirements.txt to:

```toml
From:
pyobjc-framework-Quartz>=9.0; sys_platform == 'darwin' and platform_release >= '22.0'

To:
pyobjc-framework-Quartz>=10.0; sys_platform == 'darwin' and platform_release >= '22.0'
```

and setup.py to:

```py
From:
"pyobjc-framework-Quartz>=9.0; sys_platform == 'darwin' and platform_release >= '22.0'",

To:
"pyobjc-framework-Quartz>=10.0; sys_platform == 'darwin' and platform_release >= '22.0'",
```

And it installs!

Now, the odd thing is that the requirement was originally >=9.0 which should pick up 12.1.

### Ask

Are you willing to adjust your requirements.txt and setup.py to consider pyobjc-framework-quartz>=10.00 or higher?

### Adding to the mix.. If I try with Python 3.14 it complains about pyobjc-framework-coremedia (v9.2) coming from pyobjc-framework-avfoundation (v9.2)... 

... so Python 3.14 is even more picky!

```py
      ModuleNotFoundError: No module named 'pkg_resources'

      hint: This error likely indicates that `pyobjc-framework-coremedia@9.2` depends on `pkg_resources`, but doesn't declare it as a build dependency. If `pyobjc-framework-coremedia` is a first-party package, consider
      adding `pkg_resources` to its `build-system.requires`. Otherwise, either add it to your `pyproject.toml` under:

      [tool.uv.extra-build-dependencies]
      pyobjc-framework-coremedia = ["pkg_resources"]

      or `uv pip install pkg_resources` into the environment and re-run with `--no-build-isolation`.
  help: `pyobjc-framework-coremedia` (v9.2) was included because `check-timezone` (v0.3.0) depends on `osxphotos` (v0.75.6) which depends on `pyobjc-framework-avfoundation` (v9.2) which depends on
        `pyobjc-framework-coremedia`
```

**Comment by oPromessa** [comment]
### Same Resolution on Python 3.14 and pyobjc-framework-AVFoundation. Must include in requirements >=10.0

```toml
pyobjc-framework-AVFoundation>=10.0; sys_platform == 'darwin' and platform_release >= '22.0'
```

**Comment by RhetTbull** [comment]
I'm not opposed to changing the requirements but I don't understand why this is breaking. I've tested install on python 3.14 and macOS 26.4 and it works.  I noticed you're using homebrew python. I strongly recommend installing python with uv (`uv python install 3.14`).  See [this article](https://justinmayer.com/posts/homebrew-python-is-not-for-you/) about why you shouldn't use homebrew python. TL;DR: homebrew will happily break python.

```
$ uv tool install osxphotos
Resolved 79 packages in 1.93s
Prepared 7 packages in 1.51s
Installed 79 packages in 93ms
 + appdirs==1.4.4
 + arpeggio==2.0.3
 + beautifulsoup4==4.14.3
 + bitarray==3.8.1
 + bitmath==1.3.3.1
 + bitstring==4.4.0
 + blessed==1.17.12
 + bpylist2==4.1.1
 + certifi==2026.2.25
 + cffi==2.0.0
 + cgmetadata==0.2.0
 + charset-normalizer==3.4.7
 + click==8.3.2
 + idna==3.11
 + jedi==0.19.2
 + mac-alias==2.2.3
 + makelive==0.6.2
 + mako==1.3.10
 + markdown-it-py==4.0.0
 + markdown2==2.5.5
 + markupsafe==3.0.3
 + mdurl==0.1.2
 + more-itertools==11.0.1
 + objexplore==1.6.3
 + osxmetadata==1.4.1
 + osxphotos==0.75.6
 + packaging==26.0
 + parso==0.8.6
 + pathvalidate==3.3.1
 + photoscript==0.5.3
 + pip==26.0.1
 + prompt-toolkit==3.0.52
 + psutil==7.2.2
 + ptpython==3.0.32
 + py-applescript==1.0.3
 + pycparser==3.0
 + pygments==2.20.0
 + pyobjc-core==12.1
 + pyobjc-framework-applescriptkit==12.1
 + pyobjc-framework-applescriptobjc==12.1
 + pyobjc-framework-avfoundation==12.1
 + pyobjc-framework-cocoa==12.1
 + pyobjc-framework-contacts==12.1
 + pyobjc-framework-coreaudio==12.1
 + pyobjc-framework-corelocation==12.1
 + pyobjc-framework-coremedia==12.1
 + pyobjc-framework-coreml==12.1
 + pyobjc-framework-coreservices==12.1
 + pyobjc-framework-fsevents==12.1
 + pyobjc-framework-metal==12.1
 + pyobjc-framework-photos==12.1
 + pyobjc-framework-quartz==12.1
 + pyobjc-framework-scriptingbridge==12.1
 + pyobjc-framework-uniformtypeidentifiers==12.1
 + pyobjc-framework-vision==12.1
 + pytimeparse2==1.7.1
 + pyyaml==6.0.3
 + requests==2.33.1
 + rich==13.9.4
 + rich-theme-manager==0.11.0
 + shortuuid==1.0.13
 + six==1.17.0
 + soupsieve==2.8.3
 + strpdatetime==0.4.1
 + tenacity==8.5.0
 + textx==4.3.0
 + tibs==0.5.7
 + toml==0.10.2
 + typing-extensions==4.15.0
 + tzdata==2026.1
 + urllib3==2.6.3
 + utitools==0.4.0
 + wcwidth==0.6.0
 + wheel==0.46.3
 + whenever==0.8.10
 + wrapt==1.17.3
 + wurlitzer==3.1.1
 + xattr==1.3.0
 + xdg-base-dirs==6.0.2
Installed 1 executable: osxphotos
$  osxphotos --version
osxphotos, version 0.75.6
Python 3.14.3 (main, Feb 12 2026, 00:29:58) [Clang 21.1.4 ]
Python executable: /Users/osxphotos/.local/share/uv/tools/osxphotos/bin/python
macOS 26.4.0, arm64
```

**Comment by oPromessa** [comment]
Thanks for your help. 

Will look at installing python with uv. 

But note the issue is not on "uv tool install osxphotos". That runs smoothly. 

The issue is in my GitHub own dev environment -- it's a mono repository where I build several tools under the "tools" folder -- where I build tools like check_timezone that make use of "import osxphotos". 

And the weirdest is why it does not pickup version 12.1 for
pyobjc-framework-quartz. 

Will keep on digging:investigating as I don't want to move you away from other more important topics. 

Will try to start clean and see where it takes me. 

### rambling on with details...

I've created pyproject.toml on the main repository folder and a specific pyproject.toml for each tool at, eg, tools/check_timezone/pyprpject.toml -- pyproject contents is above. 

I then `uv tool install check_timezone" for production -- that also runs fine. Hmmm. Come to think of it, it used to run fine... will double check. 

The issue is when I run the following to install the dev dependencies in the dev venv:

```bash
uv venv --clear --python 3.13
uv sync --all-packages --group dev --python 3.13
```

And o get the error. Maybe some misconfig somewhere. Will keep looking.

**Comment by RhetTbull** [comment]
I'm guessing you have a dependency somewhere that is causing a conflict and driving the resolver to a lower version of pyobjc.

**Comment by oPromessa** [comment]
#### Reported issue at https://github.com/astral-sh/uv/issues/18971 

- It seems uv is performing universal (cross-platform) resolution and taking the lowest common version across both branches, or 
- Mishandling the platform_release string comparison for two-digit Darwin kernel versions (e.g. 25.x vs 22.x)

#### Workaround

Include in pyproject.toml, for macOS 26.4

```toml
[tool.uv]
override-dependencies = [
    "pyobjc-framework-avfoundation>=12.0",
]
```

**Comment by oPromessa** [comment]
Feedback from astral/uv team on https://github.com/astral-sh/uv/issues/18971#issuecomment-4227083668

**Comment by RhetTbull** [comment]
Should probably update all the pyobjc dependencies but need to know the minimum pyobjc for each platform version. I'm busy with PhotosInspector so don't have time at the moment for this.

**Comment by oPromessa** [comment]
Sure. For now the workaround works. So. No stress. 

I can try to find the min levels.

**Comment by oPromessa** [comment]
Thanks so much for the update @RhetTbull . 

Would you mind also reviewing/checking this PR https://github.com/RhetTbull/utitools/pull/3 on utitools as it is used by osxphotos and still limits the compatibility of pyobj + MacOs 15 + python 3.13.

Whenever you can. No urgency at all.

**Comment by RhetTbull** [comment]
@oPromessa I've merged and released new version of utitools. Sorry, I missed the notification a PR was waiting.

**Comment by oPromessa** [comment]
Thank you sou much @RhetTbull 

Issue persist...I think I failed to update osxphotos/setup.py with the dependencies. I am sorry about that!

I've submitted a PR  #2148  to align requirements.txt with setup.py. Again, no urgency!
